### ISSUE TITLE
Custom HelpProvider is being overridden by the default HelpProvider

### ISSUE THREAD

**Issue by kedde** [spectreconsole/spectre.console#1360] opened 2023-11-10 07:46 UTC
**Information**
 - OS: [eg Windows]
 - Version: git(main)
 - Terminal: [e.g Windows Terminal]

**Describe the bug**

Can not register a Custom HelpProvider when using Microsoft.Extensions.DependencyInjection & Spectre.Console.Cli.Extensions.DependencyInjection. The default HelpProvider is used in stead of 
the custom help provider. 

My guess is, that the following line is overriding the HelpProvider. 

https://github.com/spectreconsole/spectre.console/blob/131b37fff858f8d5dd483ff369bb3d43a07c1e08/src/Spectre.Console.Cli/Internal/CommandExecutor.cs#L27

**To Reproduce**
Steps to reproduce the behavior.

I installed these two nuget packages: 

* Microsoft.Extensions.DependencyInjection
* Spectre.Console.Cli.Extensions.DependencyInjection

and modified the test Should_Output_Custom_Help_When_Registered_By_Instance to use 

``` c#
[Fact]
[Expectation("Custom_Help_Registered_By_Instance")]
public Task Should_Output_Custom_Help_When_Registered_By_Instance()
{
    var services = new ServiceCollection();
    var registrar = new DependencyInjectionRegistrar(services);

    // Given
    var fixture = new CommandAppTester(registrar);
    fixture.Configure(configurator =>
    {
        // Create the custom help provider
        var helpProvider = new CustomHelpProvider(configurator.Settings, "1.0");

        // Register the custom help provider instance
        registrar.RegisterInstance(typeof(IHelpProvider), helpProvider);

        configurator.SetApplicationName("myapp");
        configurator.AddCommand<DogCommand>("dog");
    });

    // When
    var result = fixture.Run();

    // Then
    return Verifier.Verify(result.Output);
}
```

**Expected behavior**

Custom HelpProvider should be used. 

**Screenshots**
![billede](https://github.com/spectreconsole/spectre.console/assets/398745/9e5c0f60-257b-44ce-8cbe-e409bc146112)

**Additional context**

**Comment by nils-a** [comment] 2023-11-10 15:43
Closing as duplicate of #1313

**Closed** 2023-11-10 15:43 UTC
Labels: bug, needs triage
