### ISSUE TITLE
Treat trailing commands as extra remaining arguments

### ISSUE THREAD

**Issue by patriksvensson** [spectreconsole/spectre.console#190] opened 2020-08-23 09:05 UTC
If the user provides a command to a leaf command and strict parsing is turned off, the trailing command should be treated as an extra remaining argument instead of showing an error.

**Comment by FrankRay78** [comment] 2022-10-09 14:17
I have tested the code snippet provided by @MiloszKrajewski above, compiled it for .Net 6.0, and I cannot reproduce this bug.

![image](https://user-images.githubusercontent.com/52075808/194761582-c219a464-c40a-43f8-9bfe-0b5e9ab6c440.png)

I recompiled the code between each run above, the latter run including the line below to turn on strict parsing.

```
    static void Main(string[] args)
    {
        var testArgs = new[] {
            "run",
            "cmd",
            "-e", "A=7",
            "-e", "B=10",
            "--",
            "cmd", "/c", "set && pause"
        };
        var app = new CommandApp();
        app.Configure(config =>
        {
            config.AddCommand<RunCommand>("run");
            config.UseStrictParsing(); //                     <-- THIS TURNS ON STRICT PARSING
        }
        );
        app.Run(testArgs);
    }
```

I propose this issue can be closed as no longer reproducible.

**Comment by FrankRay78** [comment] 2022-12-11 13:54
This issue can be closed/marked as not reproduceable @patriksvensson, due to my re-testing above: https://github.com/spectreconsole/spectre.console/issues/190#issuecomment-1272552248

**Closed** 2022-12-11 14:54 UTC
Labels: feature
