### ISSUE TITLE
TableRowCollection.Update - unnecessary copying of data?

### ISSUE THREAD

**Issue by m5x** [spectreconsole/spectre.console#813] opened 2022-04-12 18:03 UTC
Is there a reason for replacing items in List<> instances in method [TableRowCollection.Update](https://github.com/spectreconsole/spectre.console/blob/52c1d9122bce4c73ae9205e2f2aff01cba03a4c4/src/Spectre.Console/Widgets/Table/TableRowCollection.cs#L123) by removing old item and then inserting new one at the same index? This makes List<> do unnecessary copying which could be avoided by simply replacing the old item with new one (i.e. list[index] = newItem).

**Comment by patriksvensson** [comment] 2022-04-13 20:59
Not a bug, moving this to discussions.

**Closed by patriksvensson** 2022-04-13 20:59 UTC
Labels: bug
