### ISSUE TITLE
Wrong border

### ISSUE THREAD

**Issue by tamasg** [spectreconsole/spectre.console#774] opened 2022-03-21 12:23 UTC
Hello,

**Information**
 - OS: Windows
 - Version: 0.43
 - Terminal: **ONLY** Windows Terminal

**Describe the bug**
If no border color is specified, the border is broken.

**To Reproduce**
```csharp
using System;
using Spectre.Console;

namespace Header;

public static class Program
{
    public static void Main()
    {
        Console.Clear();

        var table1 = new Table();
        table1.Centered();
        // table1.BorderColor(Color.White);
        table1.AddColumn("Terminal");
        table1.AddColumn("Enviroment");
        table1.AddRow("Item 1", "Item 2");
        table1.AddRow("Item 3", "Item 4");
        table1.AddRow("Item 5", "Item 6");

        var table2 = new Table();
        table2.Centered();
        table2.BorderColor(Color.White);
        table2.AddColumn("Terminal");
        table2.AddColumn("Enviroment");
        table2.AddRow("Item 1", "Item 2");
        table2.AddRow("Item 3", "Item 4");
        table2.AddRow("Item 5", "Item 6");

        var table3 = new Table();
        table3.Centered();
        // table3.BorderColor(Color.White);
        table3.Border(TableBorder.Rounded);
        table3.AddColumn("Terminal");
        table3.AddColumn("Enviroment");
        table3.AddRow("Item 1", "Item 2");
        table3.AddRow("Item 3", "Item 4");
        table3.AddRow("Item 5", "Item 6");

        var table4 = new Table();
        table4.Centered();
        table4.BorderColor(Color.White);
        table4.Border(TableBorder.Rounded);
        table4.AddColumn("Terminal");
        table4.AddColumn("Enviroment");
        table4.AddRow("Item 1", "Item 2");
        table4.AddRow("Item 3", "Item 4");
        table4.AddRow("Item 5", "Item 6");

        AnsiConsole.Write(table1);
        AnsiConsole.Write(table2);
        AnsiConsole.Write(table3);
        AnsiConsole.Write(table4);

        Console.ReadLine();
    }
}
```
**Screenshots**
![Snag_c7e046](https://user-images.githubusercontent.com/5910815/159259779-fd6e9e04-bf09-469f-9bd4-412ec85a7981.png)

Tamas

**Comment by phil-scott-78** [comment] 2022-03-21 13:10
when you say broken are you talking about the gap? 

Nothing we can do about that. That's a combination of your terminal and font. We just write characters to the screen, not pixels.

**Comment by tamasg** [comment] 2022-03-22 01:37
Hello,

yes, i was thinking about the gap. I am a new user of Spectre.Console, I was amazed to see that too. The character appears to change if no color is specified. Thanks,

Tamas

**Comment by tamasg** [comment] 2022-03-22 03:21
I even tested it a bit. Maybe a Windows terminal problem. In the case of a normal board, this is what I wrote. But for a live board, there will be a gap when the color of the frame and text is the same.

Incomprehensible ...  :)
![Snag_71821b](https://user-images.githubusercontent.com/5910815/159401265-0b0553e1-91b4-45f3-a117-4c9e2096867c.png)

**Comment by phil-scott-78** [comment] 2022-03-22 04:08
Might be worth opening an issue with the Windows Terminal project. Seems you have a solid reproduction they might be interested in with their rendering.

**Comment by patriksvensson** [comment] 2022-03-22 08:52
Thanks for reporting this @tamasg, but I'm going ahead closing this since this is something that would need to be fixed withing Windows Terminal.

**Closed by patriksvensson** 2022-03-22 08:52 UTC
Labels: bug
