### ISSUE TITLE
Spinners not showing

### ISSUE THREAD

**Issue by LegendaryB** [spectreconsole/spectre.console#391] opened 2021-04-25 12:27 UTC
**Information**
 - OS: Windows
 - Version: 10
 - Terminal: Windows CMD, Powershell

**Describe the bug**
When using the spinner sample on the cmd or powershell I only get a bar displayed instead the dots. 

**To Reproduce**
Run the Spinner sample on windows

**Expected behavior**
The dot spinner animation

**Additional context**
I switched Spinner.Known.Default to Spinner.Known.Dot to make sure that it is really used.

**Comment by patriksvensson** [comment] 2021-04-25 13:03
You will only get the dot spinner if the terminal is capable of showing Unicode characters and the output encoding is set to something like UTF-8.

**Comment by LegendaryB** [comment] 2021-04-25 13:20
Thank you for the fast reply. Do you know if the Console supports unicode on windows? 

I added this to set the Encoding to UTF-8:
            System.Console.OutputEncoding = Encoding.UTF8;

**Comment by patriksvensson** [comment] 2021-04-25 13:43
Yes it does. Try setting the encoding to UTF-8 and you should be able to see Unicode spinners.

```powershell
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```

**Comment by LegendaryB** [comment] 2021-04-25 13:46
I set both:
System.Console.OutputEncoding = Encoding.UTF8;
System.Console.InputEncoding = Encoding.UTF8;

But only get a question mark on the windows console. Probably because of the default font

**Comment by patriksvensson** [comment] 2021-05-10 15:19
The stdout encoding needs to be set to UTF-8 or UTF-16 to display UTF-8 characters.
Try running `dotnet example info` and see what encoding is being used.

**Comment by Twinki14** [comment] 2021-05-10 15:44
Using Windows Terminal with a Command Prompt instance
![image](https://user-images.githubusercontent.com/5809130/117686592-a0fe1800-b17c-11eb-978f-89186890fc41.png)

In command prompt itself
![image](https://user-images.githubusercontent.com/5809130/117686617-a6f3f900-b17c-11eb-9d3e-030a124c04d1.png)

**Comment by patriksvensson** [comment] 2021-05-10 16:40
@Twinki14 I can't reproduce the strange output in your second image.
What do your console settings look like?

![image](https://user-images.githubusercontent.com/357872/117694091-05da6200-b1bf-11eb-821d-ba4733f4a3af.png)

**Comment by phil-scott-78** [comment] 2021-05-10 20:13
I can reproduce the line break issue on my machine with `main`.  I think I've chased it down and we'll get that fixed real soon.

But regarding the spinner - that seems like the default and desired behavior. For example, if you are overriding the encoding and getting a question mark when displaying, that to me indicates that the defaults capability detection did its job and we fell back to the safe renderer. From a library perspective, forcing the issue ourselves isn't going to be a great idea for exactly this reason. I.e. we need to make safe defaults so that y'all as developers don't get issues asking why your spinner has question marks from users not using Windows Terminal.

**Comment by Twinki14** [comment] 2021-05-11 12:27
> I can reproduce the line break issue on my machine with `main`. I think I've chased it down and we'll get that fixed real soon.
> 
> But regarding the spinner - that seems like the default and desired behavior. For example, if you are overriding the encoding and getting a question mark when displaying, that to me indicates that the defaults capability detection did its job and we fell back to the safe renderer. From a library perspective, forcing the issue ourselves isn't going to be a great idea for exactly this reason. I.e. we need to make safe defaults so that y'all as developers don't get issues asking why your spinner has question marks from users not using Windows Terminal.

Regarding the spinner, after running the info example it appears to be acting just as intended. I think the confusion here is that for running a command prompt instance, inside of/with Windows Terminal, there's support for utf8 that doesn't appear to be detected by spectre.console, but i'm also not sure if there's a way you could detect that.

I'm guessing Windows Terminal has it's own utf8 support, but only "on-top" / the way it wraps of the underlying command prompt instance.

**Comment by behnamasaei** [comment] 2022-10-07 09:13
This work for me:
1. Open cmd -> Properties -> font -> font-style = Cascadia Mono
2. Add this code:
 ```
System.Console.OutputEncoding = Encoding.UTF8;
System.Console.InputEncoding = Encoding.UTF8;
```

**Comment by IanDavidJensen** [comment] 2023-03-21 12:22
> This work for me:
> 
>     1. Open cmd -> Properties -> font -> font-style = Cascadia Mono
> 
>     2. Add this code:
> 
> 
> ```
> System.Console.OutputEncoding = Encoding.UTF8;
> System.Console.InputEncoding = Encoding.UTF8;
> ```

I can confirm this approach works here too

**Comment by nils-a** [comment] 2023-12-26 21:54
I'm going ahead and close this issue. 
The main problem has been resolved (as described in https://github.com/spectreconsole/spectre.console/issues/391#issuecomment-1271332735) by
* ensuring Encoding has been set to `UTF-8`
* using a font that can show the spinners.

If someone feels this does not resolve the initial issue, do not hesitate to open a new issue.

**Closed by nils-a** 2023-12-26 21:54 UTC
Labels: bug

**Comment by lengschder97** [comment] 2024-01-31 06:31
Hey,

i have the same issue, but with .net 8.0, which nativly support UTF-8.
Setting is the same like in issue https://github.com/spectreconsole/spectre.console/issues/113
Same code worked with previous dotnet versions just perfect.

**Comment by patriksvensson** [comment] 2024-01-31 10:57
@lengschder97 This has nothing to do with .NET, but the output encoding of the terminal you're using.
