### ISSUE TITLE
Commands section of help message does not list anything

### ISSUE THREAD

**Issue by Fed03** [spectreconsole/spectre.console#908] opened 2022-07-27 15:05 UTC
**Information**
 - OS: Mac
 - Version: 0.44.0
 - Terminal: iTerm2, Rider terminal

**Describe the bug**
When calling the the CommandApp via CLI without a default Command, the commands section of the displayed help message does not list anything.

**To Reproduce**
Just configure a CommandApp without a default command and with a bunch of standard commands, i.e.
```csharp
c.AddCommand<SendNormalizedRecordToLime>("send");
c.AddCommand<NormalizeLimeCsvCommand>("normalize");
```
Then, simply execute `dotnet run`.

**Expected behavior**
I expect to see listed the following in the commands section:

- send
- normalize

**Screenshots**
<img width="439" alt="Schermata 2022-07-27 alle 16 41 03" src="https://user-images.githubusercontent.com/1193756/181281717-f5d2f7fe-002d-44ac-b09e-32476fe36323.png">

**Comment by nils-a** [comment] 2022-08-01 22:32
@Fed03 Sorry, but I am unable to reproduce that.

The code I used was:

```cs
using Spectre.Console;
using Spectre.Console.Cli;

var app = new CommandApp();
app.Configure(c =>
{
    c.AddCommand<SendNormalizedRecordToLime>("send");
    c.AddCommand<NormalizeLimeCsvCommand>("normalize");
});
return app.Run(args);

internal abstract class BaseCommand : Command
{
    public override int Execute(CommandContext context)
    {
        AnsiConsole.MarkupLine($"Hello from [green]{GetType().Name}[/].");

        return 0;
    }
}

internal sealed class SendNormalizedRecordToLime : BaseCommand
{
}

internal sealed class NormalizeLimeCsvCommand : BaseCommand
{
}
```

Which produced the expected result of:

```text
➜  dotnet run
USAGE:
    test.dll [OPTIONS] <COMMAND>

OPTIONS:
    -h, --help       Prints help information
    -v, --version    Prints version information

COMMANDS:
    send
    normalize
```

However, I don't have access to a mac using iTerm2. 

Could you try again in another terminal?
(Am I correct in assuming your Rider Terminal is also setup to utilize iTerm2?)

**Comment by Fed03** [comment] 2022-08-06 17:58
@nils-a sorry for the late answer. I tried exactly with your code and experienced the same problem.
I tried also with the built-in terminal and with hyper.is, trying also with different shells (sh, bash) other than the default zsh.

```csharp
c.AddCommand<SendNormalizedRecordToLime>("send").WithDescription("dd");
c.AddCommand<NormalizeLimeCsvCommand>("normalize");
```

obtaining the expected result
```
➜ dotnet run
USAGE:
    Spectre.Test.dll [OPTIONS] <COMMAND>

OPTIONS:
    -h, --help       Prints help information   
    -v, --version    Prints version information
                                               
COMMANDS:
    send         dd
    normalize   
```

let me know if I can help you

**Comment by FrankRay78** [comment] 2024-01-07 19:28
Closing this issue, feel free to reopen @Fed03 if it's still an issue and you can make available a complete project / Gist that reproduces it for you.

**Closed by FrankRay78** 2024-01-07 19:28 UTC
Labels: bug, area-CLI
