### ISSUE TITLE
MassTransit registration causes exception with IBus ctor dependency

### ISSUE THREAD

**Issue by jchannon** [spectreconsole/spectre.console#1267] opened 2023-07-28 10:11 UTC
**Information**
 - OS: MacOS
 - Version: 12.6.7
 - Terminal: N/A

**Describe the bug**
When MassTransit is registered in a GenericHost all is fine when a HostedService takes in an IBus ctor dependency. If I add a Spectre command that takes in the same dependency it causes an exception.

**To Reproduce**
Repro can be seen here: https://github.com/jchannon/SpectreMT/tree/main

**Expected behavior**
Not to throw and except the dependency

**Comment by gkinsman** [comment] 2023-07-28 11:12
It looks like `Spectre.Console.Extensions.Hosting` rebuilds the `IServiceProvider` in `TypeRegistrar` after the host has built it so that it can register commands into the container after the host has started. 

Many libraries in dotnet rely on the container only being built once, so this behaviour will break those libraries. It feels like this might require a bit of rework to register everything up front before the app is run.

**Comment by patriksvensson** [comment] 2023-07-28 18:33
Ah, yeah, that seems to be the case. Can you replicate this problem without using Spectre.Console.Extensions.Hosting?

Spectre.Console.Extensions.Hosting is not a Spectre.Console project, so if the problem is in that library, I would encourage you to open an issue there.

**Comment by nils-a** [comment] 2023-09-14 20:32
@jchannon If you can spare the cycles, you can check out https://github.com/juro-org/Spectre.Console.Extensions.Hosting/pull/43 it might solve your problem. 😁

I'm going ahead and close this issue, as the underlying problem is part of https://github.com/juro-org/Spectre.Console.Extensions.Hosting/ and not of Spectre.Console.

**Closed by nils-a** 2023-09-14 20:32 UTC
Labels: bug, needs triage
